build:
  image: openjdk:8u151-jdk-alpine
  steps:
    - ./gradlew clean build -x test --stacktrace

containerBuild:
  imageName: test

 
deployment:
  # type: helm
  name: tfop-query-api
  namespace: tfop
# deployment:
#   name: techops-hello-world
#   namespace: techops
  cpu: 100m
  memory: 2Gi
  # replicas: 1
  # containerPort: 9090
  # healthCheckPath: /actuator/health 
  # healthCheckPort: 9090
  # ingressPath: /
  # iamRole: techops
  ###startupSeconds: 180

environments:
  dev-ap:
    branch: gihubaction
    cluster: tfcom-cluster
    promotion:
      to: prod-2
      mergeTo: master 
    env:
      - name: NODE_ENV_ARG
        value: production
    ingressDomains:
      - helloworld-dev1.tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
  dev-cn:
    branch: release/.*
    cluster: tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
    env:
      - name: NODE_ENV_ARG
        value: production
    ingressDomains:
      - helloworld-dev1.tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
    promotion:
      to: prod-1
      mergeTo: master      
  qa-ap:
    branch: release/.*
    cluster: tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
    env:
      - name: NODE_ENV_ARG
        value: production
    ingressDomains:
      - helloworld-dev2.tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
    promotion:
      to: prod-2
      mergeTo: master 

  ############


  prod-1:
    
    cluster: tfcom-cluster
    buildEnv:
      - name: NODE_ENV_ARG
        value: production-1
    ingressDomains:
      - helloworld-dev1.tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
  prod-2:
    
    cluster: tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
    env:
      - name: NODE_ENV_ARG
        value: production-2
    ingressDomains:
      - helloworld-dev1.tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
