build:
  image: openjdk:8u151-jdk-alpine
  steps:
    - ./gradlew clean build -x test --stacktrace

containerBuild:
  imageName: techops/techops-hello-world

  
deployment:
  name: techops-hello-world
  namespace: techops
  cpu: 100m
  memory: 1Gi
  replicas: 1
  containerPort: 9090
  healthCheckPath: /actuator/health 
  healthCheckPort: 9090
  ingressPath: /
  iamRole: techops
  # labels:
  #   component: backend
  #   sub_application: techops
  #   stack: nodejs
  #   part_of: techops
  #   stack_version: 1.0
  #   application_owner: bhanuchandra.m@thermofisher.com
  #   costcenter: 111.111
  #   snow_support: DE.IT Ops - fishersci.com
  #   website: fishersci.com
  ####startupSeconds: 180

environments:
  qa4:
    branch: integration/.*
    cluster: fscom-cluster-eu-dev1.clouddev.eu.fishersci.net
    env:
      - name: NODE_ENV_ARG
        value: production
    ingressDomains:
      - helloworld-dev1.fscom-cluster-eu-dev1.clouddev.eu.fishersci.net
    promotion:
      to: qa-us,qa-ap
      mergeTo: release/multiPR    
  qa-us:
    cluster: fscom-cluster-eu-dev1.clouddev.eu.fishersci.net
    env:
      - name: NODE_ENV_ARG
        value: production
    ingressDomains:
      - helloworld-dev2.fscom-cluster-eu-dev1.clouddev.eu.fishersci.net
    promotion:
      to: prod-us
      mergeTo: main
      
  qa-ap:
    cluster: fscom-cluster-eu-dev1.clouddev.eu.fishersci.net
    buildEnv:
      - name: DOCKER_BUILDKIT
        value: 1
    env:
      - name: NODE_ENV_ARG
        value: production
    ingressDomains:
      - helloworld-dev2.fscom-cluster-eu-dev1.clouddev.eu.fishersci.net
    promotion:
      to: prod-ap,stage
      mergeTo: main
  ########################


  prod-us:
    
    cluster: fscom-cluster-eu-qa1.cloudqa.eu.fishersci.net
    ingressDomains:
      - helloworld-dev1.fscom-cluster-eu-qa1.cloudqa.eu.fishersci.net
  
  prod-ap:
   
    cluster: fscom-cluster-na-qa1.cloudqa.fishersci.net
    ingressDomains:
      - helloworld-dev1.tfcom-cluster-na-techopsdev.clouddev.thermofisher.net

  stage:
  
    cluster: fscom-cluster-na-qa1.cloudqa.fishersci.net
    ingressDomains:
      - helloworld-dev1.tfcom-cluster-na-techopsdev.clouddev.thermofisher.net
