name: Print Current Branch

on:
  push:
    branches: 
      release/2024.01-1.0
  workflow_dispatch:

jobs:
  set_current_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Extract branch name
        shell: bash
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "branch=$branch_name" | tee -a $GITHUB_OUTPUT
          echo "branch: $branch_name"
        id: extract_branch

      - name: Check for Existing Tag
        shell: bash
        env: 
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          tag=$(echo "$BRANCH" | grep -oE "[0-9]{4}[.-][0-9]{1,2}[.-][0-9]{1,2}")
          echo "tag=v$tag"
          echo "tag: $tag"
          if [ -n "$tag" ]; then
            echo "Checking for existing tag: $tag"
            if git ls-remote --tags origin | grep -q "$tag"; then
              echo "Tag $tag already exists in repo! This branch has already been released. Version number on branch needs to be incremented."
              exit 1
            else
              echo "No existing tag found: $tag"
            fi
          else
            echo "Not checking for tag, no tag could be parsed from the branch name"
          fi

      - name: Read Pipeline YAML
        id: read_yaml
        run: |
          pipelineYaml=$(cat pipeline.yaml)
          echo "Pipeline YAML Content:"
          echo "$pipelineYaml"
#
  # use_current_branch:
  #   needs: set_current_branch
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Get Current Branch
  #       run: |
  #         current_branch=${{ needs.set_current_branch.outputs.CurrentBranch }}
  #         echo "Current Branch: $current_branch" >> $GITHUB_OUTPUT 
  #         # Use the current branch as needed in your workflow

