name: Print Current Branch

on:
  push:
  workflow_dispatch:

jobs:
  set_current_branch:
    runs-on: ubuntu-latest
    outputs:
      id: current_branch
      name: CurrentBranch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Extract branch name
        shell: bash
        run: |
          branch_name="${GITHUB_REF#refs/heads/}"
          echo "branch=$branch_name" | tee -a $GITHUB_OUTPUT
          echo "branch: $branch_name"
        id: extract_branch

      - name: Check for Existing Tag
        shell: bash
        run: |
          tag=$(git tag -l)
          if [ -n "$tag" ]; then
            echo "Checking for existing tag: $tag"
            if git ls-remote --tags origin | grep -q "$tag"; then
              echo "Tag $tag already exists in repo! This branch has already been released. Version number on branch needs to be incremented."
              exit 1
            else
              echo "No existing tag found: $tag"
            fi
          else
            echo "Not checking for tag, no tag could be parsed from the branch name"
          fi
#
  # use_current_branch:
  #   needs: set_current_branch
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Get Current Branch
  #       run: |
  #         current_branch=${{ needs.set_current_branch.outputs.CurrentBranch }}
  #         echo "Current Branch: $current_branch" >> $GITHUB_OUTPUT 
  #         # Use the current branch as needed in your workflow

