name: Dynamic Secrets Workflow

on:
  push:
    branches:
      - main

jobs:
  access-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Retrieve Repository Secrets
        id: get-secrets
        run: |
          SECRETS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/actions/secrets")

          # Extract secret names and values
          SECRET_NAMES=($(echo "$SECRETS" | jq -r '.secrets[].name'))
          for name in "${SECRET_NAMES[@]}"; do
            value=$(echo "$SECRETS" | jq -r ".secrets[] | select(.name == \"$name\") | .value")
            echo "::add-mask::$value" # Masking the secret value (optional)
            echo "export $name=\"$value\"" >> $GITHUB_ENV
          done

      - name: Display Retrieved Secrets
        run: |
          # Displaying retrieved secrets (optional, remove in production)
          env | grep -E "^SECRET_"

  use-secrets:
    needs: access-secrets
    runs-on: ubuntu-latest

    steps:
      - name: Use Retrieved Secrets
        run: |
          # Accessing retrieved secrets in another job
          echo "SECRET_ONE: $SECRET_ONE"
          echo "SECRET_TWO: $SECRET_TWO"

